kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: jsp
spec:
  replicas: 2
  selector:
    matchExpressions:
      - {key: myname, operator: In, values: [qspider, jspider, pyspider]}
      - {key: env, operator: NotIn, values: [skillrary]}
  template:
    metadata:
      name: sandesh
      labels:
        myname: qspider
    spec:
      containers:
        - name: abc
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hello-world; sleep 3 ; done"]
